version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cdhstudio
      POSTGRES_PASSWORD: cdhadmin
      POSTGRES_DB: screendoor_db
  web:
    build: .
    command: bash -c "sleep 5 && python3 manage.py runserver 0.0.0.0:8000"
    container_name: screendoor
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    stdin_open: true
    tty: true
  tika:
    image: logicalspark/docker-tikaserver
    command: docker run -d -p 9998:9998 docker-tikaserver
  selenium:
    image: selenium/standalone-firefox
    command: docker run -d -p 4444:4444 --shm-size 2g selenium/standalone-firefox:3.141.59-radium
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  celery:
    build: .
    command: python manage.py celery
    restart: always
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  celery_beat:
    build: .
    command: bash -c "sleep 10 && celery beat -A screendoor_app -l info"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  flower:
    build: .
    container_name: flower
    ports:
      - 5555:5555
    command: bash -c "sleep 15 && flower -A screendoor_app --address=0.0.0.0 --port=5555"
    volumes:
      - .:/code
    depends_on:
      - celery
