version: '3'

services:
  # Postgres Database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cdhstudio
      POSTGRES_PASSWORD: cdhadmin
      POSTGRES_DB: screendoor_db
  # Django project on gunicorn server
  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --timeout=600 --workers=2 --reload --bind=0.0.0.0:8000 screendoor_app.wsgi:application"
    container_name: django-gunicorn
    restart: always
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - db
      - rabbitmq
    links:
      - selenium
    stdin_open: true
    tty: true
  # nginx reverse proxy, load balancer, static file delivery
  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  # Message passing for celery
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
  # Async task management for Django
  celery:
    build: .
    command: python manage.py celery
    restart: always
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  # Scheduled task management for Django
  celery_beat:
    build: .
    command: bash -c "sleep 10 && celery beat -A screendoor_app --pidfile= -l info"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
  # Web-based monitoring of celery tasks
  flower:
    build: .
    container_name: flower
    ports:
      - 5555:5555
    command: bash -c "sleep 15 && flower -A screendoor_app --address=0.0.0.0 --port=5555"
    volumes:
      - .:/code
    depends_on:
      - celery
  # PDF parsing
  tika:
    image: logicalspark/docker-tikaserver
    command: docker run -d -p 9998:9998 docker-tikaserver
  # Virtual browser
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
