jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false    
    steps:
      - checkout
      - run:
          name: building and starting application
          command: |
            sed -i '/env_file/d' docker-compose.yml
            sed -i '/django.env/d' docker-compose.yml
            docker-compose up --build
      - run:
          name: run tests and create xml file
          command: |
            docker-compose exec web sh
            coverage run --source='.' manage.py test
            coverage report
            coverage xml
