jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true    # default - false    
    steps:
      - checkout
      - run:
          name: building and starting application
          command: |
            sed -i '/env_file/d' docker-compose.yml
            sed -i '/django.env/d' docker-compose.yml
            docker-compose up --build --no-start
      - run:
          name: run tests
          command: |
            python3 manage.py test
