jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker
      - run:
          name: building and starting application
          command: |
            docker-compose up -- build
      - run:
          name: run tests and create xml file
          command: |
            docker-compose exec web sh
            coverage run --source='.' manage.py test
            coverage report
            coverage xml
