# Generated by Django 2.2.1 on 2019-05-24 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screendoor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('pri', models.PositiveIntegerField()),
                ('citizenship', models.CharField(max_length=200)),
                ('priority', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('veteran_preference', models.BooleanField()),
                ('french_working_ability', models.CharField(choices=[('NA', 'None'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=200)),
                ('english_working_ability', models.CharField(choices=[('NA', 'None'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=200)),
                ('first_official_language', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], max_length=200)),
                ('written_exam', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], max_length=200)),
                ('correspondence', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], max_length=200)),
                ('interview', models.CharField(choices=[('FR', 'French'), ('EN', 'English')], max_length=200)),
                ('pdf', models.FileField(upload_to='')),
                ('ranking', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(max_length=200)),
                ('area_of_study', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('program_length', models.PositiveIntegerField()),
                ('num_years_completed', models.PositiveIntegerField()),
                ('institution', models.CharField(max_length=200)),
                ('graduation_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('complementary_question_text', models.CharField(max_length=200)),
                ('applicant_answer', models.BooleanField()),
                ('applicant_complementary_response', models.CharField(blank=True, max_length=200)),
                ('parsed_response', models.CharField(blank=True, max_length=200)),
                ('analysis', models.CharField(blank=True, max_length=200)),
                ('tabulation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, max_length=200)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('num_positions', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('classification', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('open_to', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=200)),
                ('selection_process_number', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='positions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('url_ref', models.URLField(blank=True)),
                ('applications', models.ManyToManyField(blank=True, to='screendoor.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('met', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='screendoor.Position')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='classifications_selected',
            field=models.ManyToManyField(to='screendoor.Classification'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='educations',
            field=models.ManyToManyField(to='screendoor.Education'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='questions',
            field=models.ManyToManyField(blank=True, to='screendoor.FormQuestion'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='requirements_met',
            field=models.ManyToManyField(to='screendoor.RequirementMet'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='streams_selected',
            field=models.ManyToManyField(to='screendoor.Stream'),
        ),
        migrations.AddField(
            model_name='screendooruser',
            name='positions',
            field=models.ManyToManyField(blank=True, to='screendoor.Position'),
        ),
    ]
