# Generated by Django 2.2.1 on 2019-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screendoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screendooruser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
